<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttab-proceedings [
<!-- DOCUMENT TYPE DEFINITION FOR UNITED STATES TRADEMARK TRIAL AND APPEAL BOARD (TTAB) PROCEEDINGS
Reference this DTD as PUBLIC "-//USPTO//DTD TTAB PROCEEDINGS V1.0 2004-02-13//EN"

Contact:
U.S. Patent and Trademark Office
Electronic Information Products Division
P.O. Box 1450
Alexandria, VA 22313
ipd@uspto.gov

***** START REVISION HISTORY *****
2000-09-01
1) Renamed element ttab-proceedings to ttab-proceedings enforcing all uppercase element names.
2) Changed xml encoding from "ISO-8859-1" to "UTF-8"
3) Added prolog comment with DTD identification and contact information
4) Defined initial version of V0.1 and build date of 2000-09-01.

2000-11-14
1) Added element mark-text to property group.

2000-11-15
1) Reviewed optionality requirements and made more elements optional to reflect source 
   database requirements.
2) Removed PURGE-INDICATOR element.

2001-03-21
1) Added history-text to prosecution-entry and information-text to PROCEEDING.

2002-07-1
1) Removed information-text and added status-text to proceeding-entry.
2) Added identifier to prosecution-entry.
2002-08-26
1)Added the interlocutory-attorney-name, location-code, day-in-location, charge-to-location-code, charge-to-employee-name, into proceeding-information
2)Added data-available-code into proceeding-information
2002-09-25
1)Added the int-attorney-number(employee-number) into proceeding information
2)Added identifier into party, property and address table
2004-02-13
1) Removed status-text from proceeding-entry (reference table).
***** END REVISION HISTORY **********
-->
<!ELEMENT ttab-proceedings (version , action-key-code , transaction-date , proceeding-information)>
<!ELEMENT version (version-no , version-date)>
<!ELEMENT version-no (#PCDATA)>
<!ELEMENT version-date (#PCDATA)>
<!ELEMENT action-key-code (#PCDATA)>
<!ELEMENT transaction-date (#PCDATA)>
<!ELEMENT proceeding-information (data-available-code | proceeding-entry+)>
<!ELEMENT data-available-code (#PCDATA)>
<!ELEMENT proceeding-entry (number, type-code?, filing-date?, employee-number?, interlocutory-attorney-name?, location-code?, day-in-location?, charge-to-location-code?, charge-to-employee-name?, status-update-date?, status-code?, party-information?, prosecution-history?)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT type-code (#PCDATA)>
<!ELEMENT filing-date (#PCDATA)>
<!ELEMENT employee-number (#PCDATA)>
<!ELEMENT interlocutory-attorney-name (#PCDATA)>
<!ELEMENT location-code (#PCDATA)>
<!ELEMENT day-in-location (#PCDATA)>
<!ELEMENT charge-to-location-code (#PCDATA)>
<!ELEMENT charge-to-employee-name (#PCDATA)>
<!ELEMENT status-update-date (#PCDATA)>
<!ELEMENT status-code (#PCDATA)>
<!ELEMENT party-information (party*)>
<!ELEMENT party (identifier?, role-code?, name?, orgname?, property-information?, address-information?)>
<!ELEMENT identifier (#PCDATA)>
<!ELEMENT role-code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT orgname (#PCDATA)>
<!ELEMENT property-information (property*)>
<!ELEMENT property (identifier?, serial-number?, registration-number?, mark-text?)>
<!ELEMENT serial-number (#PCDATA)>
<!ELEMENT registration-number (#PCDATA)>
<!ELEMENT mark-text (#PCDATA)>
<!ELEMENT address-information (proceeding-address*)>
<!ELEMENT proceeding-address (identifier?, type-code?, name?, orgname?, address-1?, city?, state?, country?, postcode?)>
<!ELEMENT address-1 (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT prosecution-history (prosecution-entry*)>
<!ELEMENT prosecution-entry (identifier?, code?, type-code?, due-date?, date?, history-text?)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT due-date (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT history-text (#PCDATA)>
]>
<ttab-proceedings>
  <version>
    <version-no>v1.0</version-no>
    <version-date>20040213</version-date>
  </version>
  <action-key-code>DA</action-key-code>
  <transaction-date>20180418</transaction-date>
  <proceeding-information>
    <proceeding-entry>
      <number>79187966</number>
      <type-code>EXA</type-code>
      <filing-date>20170828</filing-date>
      <location-code>845</location-code>
      <day-in-location>20170828</day-in-location>
      <status-update-date>20170828</status-update-date>
      <status-code>2</status-code>
      <party-information>
        <party>
          <identifier>855413</identifier>
          <role-code>P</role-code>
          <name>Equis Pte. Ltd.</name>
          <property-information>
            <property>
              <identifier>971861</identifier>
              <serial-number>79187966</serial-number>
              <mark-text>EQUIS</mark-text>
            </property>
          </property-information>
          <address-information>
            <proceeding-address>
              <identifier>1497431</identifier>
              <type-code>C</type-code>
              <name>BRITT L ANDERSON</name>
              <orgname>K &amp; L GATES LLP</orgname>
              <address-1>620 HANSEN WAY</address-1>
              <city>PALO ALTO</city>
              <state>CA</state>
              <country>US</country>
              <postcode>94304</postcode>
            </proceeding-address>
          </address-information>
        </party>
      </party-information>
      <prosecution-history>
        <prosecution-entry>
          <identifier>1</identifier>
          <code>158</code>
          <type-code>X</type-code>
          <date>20170828</date>
          <history-text>APPEAL TO BOARD</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>2</identifier>
          <code>155</code>
          <type-code>X</type-code>
          <date>20170828</date>
          <history-text>Appeal Acknowledged; Case Remanded</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>3</identifier>
          <code>128</code>
          <type-code>T</type-code>
          <date>20170828</date>
          <history-text>INSTITUTED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>4</identifier>
          <code>179</code>
          <type-code>X</type-code>
          <date>20170906</date>
          <history-text>PROCEEDINGS RESUMED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>5</identifier>
          <code>185</code>
          <type-code>X</type-code>
          <date>20170502</date>
          <history-text>REQ FOR RECON</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>6</identifier>
          <code>180</code>
          <type-code>X</type-code>
          <date>20171103</date>
          <history-text>JURISDICTION RESTORED / REMANDED TO EXAMINER</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>7</identifier>
          <code>424</code>
          <type-code>P</type-code>
          <date>20171124</date>
          <history-text>RECON DENIED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>8</identifier>
          <code>164</code>
          <type-code>X</type-code>
          <date>20171129</date>
          <history-text>BRIEF DUE</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>9</identifier>
          <code>157</code>
          <type-code>X</type-code>
          <date>20180123</date>
          <history-text>APPEAL BRIEF</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>10</identifier>
          <code>181</code>
          <type-code>X</type-code>
          <date>20180130</date>
          <history-text>APPEAL FORWARDED TO EXAMINER FOR BRIEF</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>11</identifier>
          <code>173</code>
          <type-code>T</type-code>
          <date>20180320</date>
          <history-text>EXAMINER'S STATEMENT</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>12</identifier>
          <code>704</code>
          <type-code>E</type-code>
          <date>20180410</date>
          <history-text>APPLICANT REQ FOR ORAL HEARING</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>13</identifier>
          <code>661</code>
          <type-code>P</type-code>
          <date>20180418</date>
          <history-text>ORAL HEARING REQUESTED; RESPONSE DUE</history-text>
        </prosecution-entry>
      </prosecution-history>
    </proceeding-entry>
    <proceeding-entry>
      <number>79188696</number>
      <type-code>EXA</type-code>
      <filing-date>20180309</filing-date>
      <location-code>845</location-code>
      <day-in-location>20180309</day-in-location>
      <status-update-date>20180309</status-update-date>
      <status-code>2</status-code>
      <party-information>
        <party>
          <identifier>879370</identifier>
          <role-code>P</role-code>
          <name>Ushio Denki Kabushiki Kaisha</name>
          <property-information>
            <property>
              <identifier>1010863</identifier>
              <serial-number>79188696</serial-number>
              <mark-text>USHIO</mark-text>
            </property>
          </property-information>
          <address-information>
            <proceeding-address>
              <identifier>1545321</identifier>
              <type-code>C</type-code>
              <name>LEIGH ANN LINDQUIST</name>
              <orgname>SUGHRUE MION PLLC</orgname>
              <address-1>2100 PENNSYLVANIA AVENUE, N.W.SUITE 800</address-1>
              <city>WASHINGTON</city>
              <state>DC</state>
              <country>US</country>
              <postcode>20037</postcode>
            </proceeding-address>
          </address-information>
        </party>
      </party-information>
      <prosecution-history>
        <prosecution-entry>
          <identifier>1</identifier>
          <code>158</code>
          <type-code>X</type-code>
          <date>20180309</date>
          <history-text>APPEAL TO BOARD</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>2</identifier>
          <code>155</code>
          <type-code>X</type-code>
          <date>20180309</date>
          <history-text>Appeal Acknowledged; Case Remanded</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>3</identifier>
          <code>128</code>
          <type-code>T</type-code>
          <date>20180309</date>
          <history-text>INSTITUTED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>4</identifier>
          <code>185</code>
          <type-code>X</type-code>
          <date>20180309</date>
          <history-text>REQ FOR RECON</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>5</identifier>
          <code>424</code>
          <type-code>P</type-code>
          <date>20180406</date>
          <history-text>RECON DENIED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>6</identifier>
          <code>179</code>
          <type-code>X</type-code>
          <date>20180418</date>
          <history-text>PROCEEDINGS RESUMED</history-text>
        </prosecution-entry>
      </prosecution-history>
    </proceeding-entry>
    <proceeding-entry>
      <number>79190008</number>
      <type-code>EXT</type-code>
      <filing-date>20180308</filing-date>
      <location-code>845</location-code>
      <day-in-location>20180308</day-in-location>
      <status-update-date>20180418</status-update-date>
      <status-code>9</status-code>
      <party-information>
        <party>
          <identifier>879244</identifier>
          <role-code>P</role-code>
          <name>Vintage Wine Estates, Inc.</name>
          <property-information />
          <address-information>
            <proceeding-address>
              <identifier>1545062</identifier>
              <type-code>C</type-code>
              <name>Ron Oines</name>
              <orgname>Rutan &amp; Tucker, LLP</orgname>
              <address-1>611 Anton Blvd. Suite 1400</address-1>
              <city>Costa Mesa</city>
              <state>CA</state>
              <country>US</country>
              <postcode>92626</postcode>
            </proceeding-address>
          </address-information>
        </party>
        <party>
          <identifier>879245</identifier>
          <role-code>D</role-code>
          <name>Peter Lehmann Wines Pty Limited</name>
          <property-information>
            <property>
              <identifier>1010606</identifier>
              <serial-number>79190008</serial-number>
              <mark-text>LAYERS</mark-text>
            </property>
          </property-information>
          <address-information>
            <proceeding-address>
              <identifier>1545064</identifier>
              <type-code>C</type-code>
              <name>Alfred W. Zaher</name>
              <orgname>BUCHANAN INGERSOLL &amp; ROONEY PC</orgname>
              <address-1>50 S. 16th Street, Suite 3200 Two Liberty Place</address-1>
              <city>Philadelphia</city>
              <state>PA</state>
              <postcode>19102-2555</postcode>
            </proceeding-address>
          </address-information>
        </party>
      </party-information>
      <prosecution-history>
        <prosecution-entry>
          <identifier>1</identifier>
          <code>1000</code>
          <type-code>T</type-code>
          <date>20180308</date>
          <history-text>INCOMING - EXT TIME TO OPPOSE FILED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>2</identifier>
          <code>1011</code>
          <type-code>T</type-code>
          <date>20180308</date>
          <history-text>EXTENSION OF TIME GRANTED</history-text>
        </prosecution-entry>
      </prosecution-history>
    </proceeding-entry>
    <proceeding-entry>
      <number>79191002</number>
      <type-code>EXA</type-code>
      <filing-date>20171020</filing-date>
      <location-code>845</location-code>
      <day-in-location>20171020</day-in-location>
      <status-update-date>20171020</status-update-date>
      <status-code>2</status-code>
      <party-information>
        <party>
          <identifier>862113</identifier>
          <role-code>P</role-code>
          <name>P.G.A. Electronic</name>
          <property-information>
            <property>
              <identifier>982533</identifier>
              <serial-number>79191002</serial-number>
              <mark-text>CARAT</mark-text>
            </property>
          </property-information>
          <address-information>
            <proceeding-address>
              <identifier>1510836</identifier>
              <type-code>C</type-code>
              <name>DEBORAH L CORPUS</name>
              <orgname>PEARNE &amp; GORDON LLP</orgname>
              <address-1>1801 E 9TH ST STE 1200</address-1>
              <city>CLEVELAND</city>
              <state>OH</state>
              <country>US</country>
              <postcode>44114-3108</postcode>
            </proceeding-address>
          </address-information>
        </party>
      </party-information>
      <prosecution-history>
        <prosecution-entry>
          <identifier>1</identifier>
          <code>158</code>
          <type-code>X</type-code>
          <date>20171020</date>
          <history-text>APPEAL TO BOARD</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>2</identifier>
          <code>155</code>
          <type-code>X</type-code>
          <date>20171020</date>
          <history-text>APPEAL ACKNOWLEDGED; CASE REMANDED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>3</identifier>
          <code>128</code>
          <type-code>T</type-code>
          <date>20171020</date>
          <history-text>INSTITUTED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>4</identifier>
          <code>185</code>
          <type-code>X</type-code>
          <date>20170925</date>
          <history-text>REQ FOR RECON</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>5</identifier>
          <code>424</code>
          <type-code>P</type-code>
          <date>20171119</date>
          <history-text>RECON DENIED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>6</identifier>
          <code>179</code>
          <type-code>X</type-code>
          <date>20171122</date>
          <history-text>PROCEEDINGS RESUMED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>7</identifier>
          <code>157</code>
          <type-code>X</type-code>
          <date>20180122</date>
          <history-text>APPEAL BRIEF</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>8</identifier>
          <code>181</code>
          <type-code>X</type-code>
          <date>20180129</date>
          <history-text>APPEAL FORWARDED TO EXAMINER FOR BRIEF</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>9</identifier>
          <code>173</code>
          <type-code>T</type-code>
          <date>20180329</date>
          <history-text>EXAMINER'S STATEMENT</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>10</identifier>
          <code>183</code>
          <type-code>X</type-code>
          <date>20180417</date>
          <history-text>REPLY BRIEF</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>11</identifier>
          <code>174</code>
          <type-code>T</type-code>
          <date>20180418</date>
          <history-text>MEMO FORWARDING REPLY BRIEF</history-text>
        </prosecution-entry>
      </prosecution-history>
    </proceeding-entry>
    <proceeding-entry>
      <number>79194915</number>
      <type-code>EXT</type-code>
      <filing-date>20180418</filing-date>
      <location-code>845</location-code>
      <day-in-location>20180418</day-in-location>
      <status-update-date>20180418</status-update-date>
      <status-code>1</status-code>
      <party-information>
        <party>
          <identifier>884636</identifier>
          <role-code>P</role-code>
          <name>Information Builders, Inc.</name>
          <property-information />
          <address-information>
            <proceeding-address>
              <identifier>1555837</identifier>
              <type-code>C</type-code>
              <name>Howard F. Mandelbaum</name>
              <orgname>Levine Mandelbaum PLLC</orgname>
              <address-1>222 Bloomingdale RoadSuite 203</address-1>
              <city>White Plains</city>
              <state>NY</state>
              <country>US</country>
              <postcode>10605</postcode>
            </proceeding-address>
          </address-information>
        </party>
        <party>
          <identifier>884637</identifier>
          <role-code>D</role-code>
          <name>Focusrite Audio Engineering Limited</name>
          <property-information>
            <property>
              <identifier>1019983</identifier>
              <serial-number>79194915</serial-number>
              <mark-text>FOCUSRITE</mark-text>
            </property>
          </property-information>
          <address-information>
            <proceeding-address>
              <identifier>1555839</identifier>
              <type-code>C</type-code>
              <name>Steven A. Abreu</name>
              <orgname>SUNSTEIN KANN MURPHY &amp; TIMBERS LLP</orgname>
              <address-1>125 Summer Street</address-1>
              <city>Boston</city>
              <state>MA</state>
              <postcode>02110</postcode>
            </proceeding-address>
          </address-information>
        </party>
      </party-information>
      <prosecution-history>
        <prosecution-entry>
          <identifier>1</identifier>
          <code>1000</code>
          <type-code>T</type-code>
          <date>20180418</date>
          <history-text>INCOMING - EXT TIME TO OPPOSE FILED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>2</identifier>
          <code>1011</code>
          <type-code>T</type-code>
          <date>20180418</date>
          <history-text>EXTENSION OF TIME GRANTED</history-text>
        </prosecution-entry>
      </prosecution-history>
    </proceeding-entry>
    <proceeding-entry>
      <number>79195723</number>
      <type-code>EXT</type-code>
      <filing-date>20180412</filing-date>
      <location-code>845</location-code>
      <day-in-location>20180213</day-in-location>
      <status-update-date>20180412</status-update-date>
      <status-code>1</status-code>
      <party-information>
        <party>
          <identifier>876320</identifier>
          <role-code>P</role-code>
          <name>Gillyboo Corporation</name>
          <property-information />
          <address-information>
            <proceeding-address>
              <identifier>1539223</identifier>
              <type-code>C</type-code>
              <name>MARY MARGARET L ODONNELL</name>
              <orgname>BLUE FILAMENT LAW PLLC</orgname>
              <address-1>700 E MAPLE , SUITE 450</address-1>
              <city>BIRMINGHAM</city>
              <state>MI</state>
              <country>US</country>
              <postcode>48009</postcode>
            </proceeding-address>
          </address-information>
        </party>
        <party>
          <identifier>876321</identifier>
          <role-code>D</role-code>
          <name>Lynx ApS</name>
          <property-information>
            <property>
              <identifier>1005787</identifier>
              <serial-number>79195723</serial-number>
              <mark-text>HALO</mark-text>
            </property>
          </property-information>
          <address-information>
            <proceeding-address>
              <identifier>1539225</identifier>
              <type-code>C</type-code>
              <name>LEW HANSEN</name>
              <orgname>SHERIDAN ROSS PC</orgname>
              <address-1>1560 BROADWAY, SUITE 1200</address-1>
              <city>DENVER</city>
              <state>CO</state>
              <country>US</country>
              <postcode>80202</postcode>
            </proceeding-address>
          </address-information>
        </party>
      </party-information>
      <prosecution-history>
        <prosecution-entry>
          <identifier>1</identifier>
          <code>1000</code>
          <type-code>T</type-code>
          <date>20180213</date>
          <history-text>INCOMING - EXT TIME TO OPPOSE FILED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>2</identifier>
          <code>1011</code>
          <type-code>T</type-code>
          <date>20180213</date>
          <history-text>EXTENSION OF TIME GRANTED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>3</identifier>
          <code>1000</code>
          <type-code>T</type-code>
          <date>20180412</date>
          <history-text>INCOMING - EXT TIME TO OPPOSE FILED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>4</identifier>
          <code>1011</code>
          <type-code>T</type-code>
          <date>20180418</date>
          <history-text>EXT GRANTED</history-text>
        </prosecution-entry>
      </prosecution-history>
    </proceeding-entry>
    <proceeding-entry>
      <number>79197154</number>
      <type-code>EXT</type-code>
      <filing-date>20180418</filing-date>
      <location-code>845</location-code>
      <day-in-location>20180418</day-in-location>
      <status-update-date>20180418</status-update-date>
      <status-code>1</status-code>
      <party-information>
        <party>
          <identifier>884574</identifier>
          <role-code>P</role-code>
          <name>OERLIKON SCHWEISSTECHNIK AG</name>
          <property-information />
          <address-information>
            <proceeding-address>
              <identifier>1555719</identifier>
              <type-code>C</type-code>
              <name>Thomas M. Williams</name>
              <orgname>Ulmer &amp; Berne LLP</orgname>
              <address-1>500 West Madison St., Suite 3600</address-1>
              <city>Chicago</city>
              <state>IL</state>
              <country>US</country>
              <postcode>60661</postcode>
            </proceeding-address>
          </address-information>
        </party>
        <party>
          <identifier>884575</identifier>
          <role-code>D</role-code>
          <name>Oerlikon Vermögens-Verwaltungs GmbH</name>
          <property-information>
            <property>
              <identifier>1019818</identifier>
              <serial-number>79197154</serial-number>
              <mark-text>OERLIKON</mark-text>
            </property>
          </property-information>
          <address-information>
            <proceeding-address>
              <identifier>1555721</identifier>
              <type-code>C</type-code>
              <name>Neil B. Friedman</name>
              <orgname>HODGSON RUSS LLP</orgname>
              <address-1>605 Third Avenue, Suite 2300</address-1>
              <city>New York, NY</city>
              <postcode>10158</postcode>
            </proceeding-address>
          </address-information>
        </party>
      </party-information>
      <prosecution-history>
        <prosecution-entry>
          <identifier>1</identifier>
          <code>1000</code>
          <type-code>T</type-code>
          <date>20180418</date>
          <history-text>INCOMING - EXT TIME TO OPPOSE FILED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>2</identifier>
          <code>1011</code>
          <type-code>T</type-code>
          <date>20180418</date>
          <history-text>EXTENSION OF TIME GRANTED</history-text>
        </prosecution-entry>
      </prosecution-history>
    </proceeding-entry>
    <proceeding-entry>
      <number>79198802</number>
      <type-code>EXA</type-code>
      <filing-date>20180110</filing-date>
      <location-code>845</location-code>
      <day-in-location>20180110</day-in-location>
      <status-update-date>20180323</status-update-date>
      <status-code>9</status-code>
      <party-information>
        <party>
          <identifier>872575</identifier>
          <role-code>P</role-code>
          <name>AS Liviko</name>
          <property-information>
            <property>
              <identifier>999007</identifier>
              <serial-number>79198802</serial-number>
              <mark-text>CRAFT DISTILLED BATCH NO 001 RECIPE NO 023 CRAFT D</mark-text>
            </property>
          </property-information>
          <address-information>
            <proceeding-address>
              <identifier>1531653</identifier>
              <type-code>C</type-code>
              <name>BRUCE L ADAMS</name>
              <orgname>KLINTWORTH &amp; ROZENBLAT IP LLP</orgname>
              <address-1>17 BATTERY PLACE STE 906</address-1>
              <city>NEW YORK</city>
              <state>NY</state>
              <country>US</country>
              <postcode>10004</postcode>
            </proceeding-address>
          </address-information>
        </party>
      </party-information>
      <prosecution-history>
        <prosecution-entry>
          <identifier>1</identifier>
          <code>158</code>
          <type-code>X</type-code>
          <date>20180110</date>
          <history-text>APPEAL TO BOARD</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>2</identifier>
          <code>155</code>
          <type-code>X</type-code>
          <date>20180111</date>
          <history-text>APPEAL ACKNOWLEDGED; CASE REMANDED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>3</identifier>
          <code>128</code>
          <type-code>T</type-code>
          <date>20180111</date>
          <history-text>INSTITUTED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>4</identifier>
          <code>185</code>
          <type-code>X</type-code>
          <date>20180110</date>
          <history-text>REQ FOR RECON</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>5</identifier>
          <code>802</code>
          <type-code>T</type-code>
          <date>20180323</date>
          <history-text>BD DECISION: DISMISSED</history-text>
        </prosecution-entry>
        <prosecution-entry>
          <identifier>6</identifier>
          <code>999</code>
          <type-code>N</type-code>
          <date>20180323</date>
          <history-text>TERMINATED</history-text>
        </prosecution-entry>
      </prosecution-history>
    </proceeding-entry>
    <proceeding-entry>
      <number>79198802</number>
      <type-code>EXT</type-code>
      <filing-date>20180321</filing-date>
      <employee-number>0</employee-number>
      <interlocutory-attorney-name>SYSTEM ADMIN</interlocutory-attorney-name>
      <location-code>845</location-code>
      <day-in-location>20180418</day-in-location>
      <status-update-date>20180321</status-update-date>
      <status-code>1</status-code>
      <party-information>
        <party>